### ISSUE TITLE
Public class methods as rpc methods

### ISSUE THREAD

**Issue by jamalo** [timiki/rpc-server-bundle#12]
Hello!

Can we achieve for this bundle something like this:

```
calls: 
{"jsonrpc": "2.0", "method": "user.create", "params": {"email": "test@example.com"}}
{"jsonrpc": "2.0", "method": "user.delete", "params": {"id": 1}}

// service that is subscribed
class UserService
{
    public function create(string $email)
    {
        return ['user created'];
    }

    // transfer id to object for example: https://symfony.com/doc/master/form/data_transformers.html
    public function delete(User $user)
    {
        return ['user deleted'];
    }
}

App\Service\UserService:
     tags:
         - { name: 'rpc.server.expose??', method: 'user' }

```

This would mean that services with public methods are exposed as user.{create, delete} etc.  This would make it unnecessary to create for every method an @RPC\Method with execute.

**Comment by netesin** [comment]
Hi, 

Let's look at it:

- more difficult parameter validation
- method begin violation The Single Responsibility Principle
- you want to have one big service at all, with many dependencies

I don't believe this structure will be useful, in begin of create bundle i have a similar vision, but it's like REST through an RPC

**Comment by jamalo** [comment]
Thanks for your answer! Fair enough. But what about dependency injection in the methods? This would mean we need to get the service via the container directly using the container interface. What about using entities in the methods? Entities have validation in their own class. Do we need to create an data transformer (id to object)?

**Comment by netesin** [comment]
> But what about dependency injection in the methods? 
It must be work by default, just use constructor for inject services

**Comment by jamalo** [comment]
You are right, forgot about the new autowiring

**Comment by netesin** [comment]
About data transformer, we've already discussed with @lvovgeka  about enhancement functionality (merge with Form functional), but not gone far in this question ((  

for example, it could look like something that

```

  /**
     * @Rpc\Param(name="id")
     * @Rpc\Entity(class="User", field="id")
     */
    protected $user;

```

But it will be work only for simple entity request, and you must anyway inject EntityManager in constructor for apply changes. If it will be ActiveRecord (🥴) it will be more more logically, so it is not yet clear whether this would be useful

@lvovgeka have any ideas?

**Comment by jamalo** [comment]
We can maybe use `$this->entityManager->getReference('App\Entity\User', 1234);` for converting

**Comment by lvovgeka** [comment]
> About data transformer, we've already discussed with @lvovgeka about enhancement functionality (merge with Form functional), but not gone far in this question ((
> 
> for example, it could look like something that
> 
> ```
> 
>   /**
>      * @Rpc\Param(name="id")
>      * @Rpc\Entity(class="User", field="id")
>      */
>     protected $user;
> ```
> 
> But it will be work only for simple entity request, and you must anyway inject EntityManager in constructor for apply changes. If it will be ActiveRecord (🥴) it will be more more logically, so it is not yet clear whether this would be useful
> 
> @lvovgeka have any ideas?

Hi all.

- if we implement `entity` and `dto` converting like:
```php
  /**
     * @Rpc\Entity(class="someEntitity", param="id")
     */
    protected $someEntitity;
  /**
     * @Rpc\DTO(class="someDto", params={"p1", "p2", ...})
     */
    protected $someDto;
```
I think it's will be very complicated. 

---

if we implement injection `resource` into methods like:

```php
    public function editMethod(User $user)
    {
            ...
    }
```
In this case I think json request should be like:
```json
{"jsonrpc": "2.0", "method": "user.edit.{id}", "params": {"email": "test@example.com"}}
```
Where `id` is dynamic, but it not meet specifications https://www.jsonrpc.org/specification

**Comment by jamalo** [comment]
I think this we shoud go for this way, since the above example does not meet the specification:
`{"jsonrpc": "2.0", "method": "user.edit", "params": {"id": "1", "fields": {"email": "test@example.com"}}}
`
This means when working with entities we need to specify the id (primary key) and the fields like above
@netesin @lvovgeka

**Comment by netesin** [comment]
I think we're taking a pause on this issue.

At the moment, all the solutions require a large redesign of the bundle: new mapping, design entity methods

**Comment by jamalo** [comment]
https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html Should do the job. Makes it easier.

________________________________
Van: Nikita Netyosin <notifications@github.com>
Verzonden: Saturday, October 26, 2019 4:58:12 PM
Aan: timiki/rpc-server-bundle <rpc-server-bundle@noreply.github.com>
CC: Jamal <jamal14@hotmail.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [timiki/rpc-server-bundle] Public class methods as rpc methods (#12)


I think we're taking a pause on this issue.

At the moment, all the solutions require a large redesign of the bundle: new mapping, design entity methods

**Comment by jamalo** [comment]
https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html Should do the job. Makes it easier.

**Comment by netesin** [comment]
> https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html Should do the job. Makes it easier.

Sadly, but it not help.

> Should do the job
It only work on controllers, RPC use only controller for handle request and self processes the request

> Makes it easier.
No, you're still gonna have to write an annotation handler

I think you need to understand how doctrine annotation works. As I've written above so far, I'm not ready to invest time in this development. In any case, you can always make a fork project and do everything you need 🖖

**Comment by jamalo** [comment]
I will look for a solution and create a pull request @netesin Thanks! We can close the issue for now.
