### ISSUE TITLE
http_handler error in controller

### ISSUE THREAD

**Issue by jamalo** [timiki/rpc-server-bundle#13]
Fresh install gives the following error:
`Service "rpc.server.http_handler" not found: did you mean "rpc.server.http_handler.default"? Anyway, the container inside "App\Controller\UserController" is a smaller service locator that only knows about the "http_kernel", "parameter_bag", "request_stack", "router", "serializer" and "session" services. Try using dependency injection instead.`

composer.json:
```
...
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "symfony/console": "4.3.*",
        "symfony/dotenv": "4.3.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "4.3.*",
        "symfony/yaml": "4.3.*",
        "timiki/rpc-server-bundle": "^4.1"
    },
    "require-dev": {
        "symfony/maker-bundle": "^1.13"
    },
....
```

Do we need to update https://github.com/timiki/rpc-server-bundle#controller since controller is deprecated since Symfony 4.2 and we need to use AbstractController

Using the following code works:

```
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends Controller
{
    /**
     * @Route("/json-rpc", name="json-rpc", methods={"GET", "POST"})
     */
    public function index(Request $request)
    {
        return $this->get('rpc.server.http_handler.default')->handleHttpRequest($request);
    }
}
```

**Comment by jamalo** [comment]
Also when creating the following method the response is empty:
```
<?php

namespace App\Method;

use Timiki\Bundle\RpcServerBundle\Mapping as RPC;

/**
 * @RPC\Method("user")
 */
class UserMethod
{
    /**
     * @Rpc\Param()
     */
    protected $param;

    /**
     * @Rpc\Execute()
     */
    public function execute()
    {
        return ['user info'];
    }
}
```
http://prntscr.com/pmrkh2

**Comment by netesin** [comment]
Hi, I'll see what the problem 🤔

**Comment by netesin** [comment]
> Fresh install gives the following error:

I check on new project and it no have this problem, i think you catch this error after update and apply recipes

default route look like

config/routes/rpc_server.yaml

```
rpc:
    path:     /rpc
    defaults: { _controller: RpcServerBundle:Rpc:handler }
    methods:  [POST]
```
  
class: vendor/timiki/rpc-server-bundle/src/Controller/RpcController.php

in doc not valid desc about costume controller ( i fix it in new release

by default in bundle set 1 handler 'default', you can use many different dir for handling methods, each dir  = handler

> Do we need to update https://github.com/timiki/rpc-server-bundle#controller since controller is deprecated since Symfony 4.2 and we need to use AbstractController

RpcController already use  AbstractController )

i recommend use default controller

```
rpc:
    path:     /rpc
    defaults: { _controller: RpcServerBundle:Rpc:handler }
    methods:  [POST]
```

or use yourself, that you've written. 
In you controller you can delete GET, RPC work only on POST methods

one of the specific you must add dir Method to exclude if use autowire on App, i update doc about this case

```
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity, Method, Migrations,Tests,Kernel.php}'
```

**Comment by jamalo** [comment]
I will debug the problem @netesin

**Comment by netesin** [comment]
@jamalo hi, where the problem was?

**Comment by jamalo** [comment]
Problem found, forgot the id in the body request! Without the id the request is an notification, which returns an empty response. 

_Specification: The Server MUST NOT reply to a Notification, including those that are within a batch request._

notification:
`{"jsonrpc": "2.0", "method": "user", "params": {}}`
rpc call:
`{"jsonrpc": "2.0", "method": "user", "params": {}, "id": 1}`
@netesin

**Comment by netesin** [comment]
@jamalo 👌
