### ISSUE TITLE
Permission annotation for properties

### ISSUE THREAD

**Issue by j-mywheels** [timiki/rpc-server-bundle#7]
Hello,

Can we add permission annotations for properties in entities, the bundle already supports this for roles with @Rpc\Roles annotation for classes.

//Example
class Book
{
    /**
      * @Rpc\Groups({"OBJECT_OWNER", "ADMIN"}) // or
      * @Rpc\View({"OBJECT_OWNER", "ADMIN"})
     */
    public $name;

Thanks!

**Comment by netesin** [comment]
Hi, Jamal 

We speak about rpc method properties?

```

/**
 * @RPC\Method("book")
 * @Rpc\Roles({"Some_Role"})
 */
class Book
{

    /**
     * @Rpc\Param
     */
     protected $name;

```

**Comment by j-mywheels** [comment]
It can be method properties for classes with the rpc method annotation. This would make it possible to view the name of the book if you have the **view** permission and the created date if you have the **admin** permission for example.

We can than use Symfony Voters (https://symfony.com/doc/current/security/voters.html#creating-the-custom-voter) to determine when an user can view/edit/.. an property.

**Comment by netesin** [comment]
I think we should split up two different layers

**Method**

Like the controller, it serves to process an incoming request and get a response in the form of data (and it can be anything, entity, array...) in our services it return Entity object, but on api gate it return array ))

You can use JsonPreExecuteEvent for you middleware, for example AuthorizationCheckerSubscriber use it for check roles 

**Serialization of data**

This is where you need the logic you wrote above, for example you can create our own service for serialization 

```
use Timiki\Bundle\RpcServerBundle\Serializer\SerializerInterface;

class MySerializer implements SerializerInterface {

  public function serialize($data) {
    // code here
  } 

}
```

then use it

```
// config/packages/rpc_server.yaml
rpc_server:
    serializer: 'MySerializer' // service id
```

And in serializer you can use symfony (or JMS) @Groups based on user roles (for example) and controls you output

mixing two different layers is a bad idea 🙈

**Comment by j-mywheels** [comment]
Thanks for your explanation @netesin :+1: 

```
// config/packages/rpc_server.yaml
rpc_server:
    serializer: 'MySerializer'

```

Should do the job indeed with @groups from symfony combined with the custom serializer.

**Comment by netesin** [comment]
By default it simple serialize without any context 

```
vendor/timiki/rpc-server-bundle/src/Serializer/BaseSerializer.php
 ```

you need something like this 

```
<?php

namespace App\Serializer;

use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Serializer;
use Timiki\Bundle\RpcServerBundle\Serializer\SerializerInterface;

class MySerializer implements SerializerInterface
{
    /**
     * @var Serializer
     */
    private $serializer;

    /**
     * @var UserInterface|null
     */
    private $user;

    /**
     * @param \Symfony\Component\Serializer\Serializer  $serializer
     * @param \Symfony\Component\Security\Core\Security $security
     */
    public function __construct(Serializer $serializer, Security $security)
    {
        $this->serializer = $serializer;
        $this->user = $security->getUser();
    }

    /**
     * Serialize data.
     *
     * @param mixed        $data
     * @param array|string $group
     *
     * @return array
     */
    public function serialize($data, $group = null)
    {
        return \json_decode(
            $this->serializer->serialize(
                $data,
                'json',
                ['groups' => $this->user->getRoles()]
            ),
            true
        );
    }
}
```

**Comment by j-mywheels** [comment]
Thanks! Should we support the serializer with groups in this bundle or only provide the base serializer? If not we can close this issue. Thanks @netesin

**Comment by netesin** [comment]
I thin i can add new alternative serializer and extend documentation about this case 

@j-mywheels thanks for interesting issue 💪

**Comment by netesin** [comment]
update in 4.1.2
